#!/usr/bin/env python3

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import os

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    SSO_URL=(str, "https://sso.codata.pb.gov.br/auth"),
    SSO_REALM=(str, "paraiba"),
    SSO_CLIENT_ID=(str, "cadastro_de_jogos"),
    SSO_CLIENT_SECRET=str,
    USERS_STAFF=(list, []),  # usuários que podem se logar no admin
    USERS_SUPERUSER=(list, []),  # superusuários
    STATIC_URL=(str, "static/"),
    STATIC_ROOT=(Path, BASE_DIR / "staticfiles"),
    MEDIA_URL=(str, "media/"),
    MEDIA_ROOT=(Path, BASE_DIR / "media"),
    LOGOUT_REDIRECT_URL=(str, "/oidc/login/")
)

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    env("SECRET_KEY") if not DEBUG else env("SECRET_KEY", default="django-secret-key")
)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    "_core",
    "codata_sso",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # Mozilla Django OIDC https://mozilla-django-oidc.readthedocs.io/
    "mozilla_django_oidc",

    # Debug Toolbar https://django-debug-toolbar.readthedocs.io/
    "debug_toolbar",

    # Health Checks https://django-watchman.readthedocs.io/
    'watchman',

    # Crispy Forms https://django-crispy-forms.readthedocs.io/
    "crispy_forms",
    "crispy_bootstrap5",

    # Django Reversion https://django-reversion.readthedocs.io/
    "reversion",

    # Project apps
    
    "danca",
]

DEBUG=True

AUTH_USER_MODEL = "_core.User"

AUTHENTICATION_BACKENDS = [
    "codata_sso.auth_backend.SSOAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

if DEBUG:
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
    ]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "mozilla_django_oidc.middleware.SessionRefresh",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "_conf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'danca' / 'templates'],  
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "_conf.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": env("DATABASE_HOST"),
        "PORT": env("DATABASE_PORT"),
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USERNAME"),
        "PASSWORD": env("DATABASE_PASSWORD"),
    }
}

CACHES = {
    "default": env.cache_url(default="locmemcache://" if not DEBUG else "dummycache://")
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Recife"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = env("STATIC_URL")
STATIC_ROOT = env("STATIC_ROOT")

MEDIA_URL = env("MEDIA_URL")
MEDIA_ROOT = env("MEDIA_ROOT")

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    "127.0.0.1",
]

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "default": {
            "format": "{asctime} {levelname:<8} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": env("LOG_LEVEL", default="INFO" if DEBUG else "WARNING"),
            "formatter": "default",
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "apps": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = env("LOGOUT_REDIRECT_URL")
LOGIN_URL = '/oidc/login/'

# SSO
USERS_STAFF = env.list("USERS_STAFF")
USERS_SUPERUSER = env.list("USERS_SUPERUSER")

SSO_URL = env("SSO_URL")
SSO_REALM = env("SSO_REALM")

SSO_ISSUER_URL = f"{SSO_URL}/realms/{SSO_REALM}"
SSO_CLIENT_ID = env("SSO_CLIENT_ID")
SSO_CLIENT_SECRET = env("SSO_CLIENT_SECRET")


# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Watchman (health check)
WATCHMAN_TOKENS = env("WATCHMAN_TOKENS", default=None)
WATCHMAN_CHECKS = [
    "watchman.checks.databases",
    "watchman.checks.caches"
]
