# Generated by Django 5.1.4 on 2025-04-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cache', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('local_partida', models.CharField(blank=True, max_length=100, null=True)),
                ('local_volta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='planejamento',
            options={'ordering': ['-id'], 'verbose_name': 'Planejamento', 'verbose_name_plural': 'Planejamentos'},
        ),
        migrations.CreateModel(
            name='ProfissionalEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.evento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissional_evento_set', to='danca.profissional')),
            ],
            options={
                'verbose_name': 'Evento do Profissional',
                'verbose_name_plural': 'Eventos dos Profissionais',
                'unique_together': {('profissional', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='eventos',
            field=models.ManyToManyField(related_name='profissionais_eventos', through='danca.ProfissionalEvento', to='danca.evento'),
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
    ]
