# Generated by Django 5.1.4 on 2025-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0002_profissional_alter_planejamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
