# Generated by Django 5.1.4 on 2025-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0003_profissional_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='cache',
            new_name='valor_hora_aula',
        ),
        migrations.AddField(
            model_name='profissional',
            name='qt_aulas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
