# Generated by Django 5.1.4 on 2025-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0004_rename_cache_profissional_valor_hora_aula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Entrada Externa',
                'verbose_name_plural': 'Entradas Externas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SaidaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Saída Externa',
                'verbose_name_plural': 'Saídas Externas',
                'ordering': ['-data'],
            },
        ),
    ]
