# Generated by Django 5.1.4 on 2025-04-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0005_entradaexterna_saidaexterna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntradaExterna',
            new_name='Entrada',
        ),
        migrations.RenameModel(
            old_name='SaidaExterna',
            new_name='Saida',
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-data'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='saida',
            options={'ordering': ['-data'], 'verbose_name': 'Saída', 'verbose_name_plural': 'Saídas'},
        ),
    ]
