# Generated by Django 5.1.4 on 2025-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0007_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_pagamento'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_proximo_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
