# Generated by Django 5.1.4 on 2025-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0008_alter_pagamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'get_latest_by': 'data_pagamento', 'ordering': ['-data_pagamento'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='pagamento',
            name='numero_parcela',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
