# Generated by Django 5.1.4 on 2025-05-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0009_alter_pagamento_options_pagamento_numero_parcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='numero_parcela',
        ),
    ]
