# Generated by Django 5.1.4 on 2025-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0010_remove_pagamento_numero_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='numero_parcela',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
