# Generated by Django 5.1.4 on 2025-09-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0016_pedidocamisa_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocamisa',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('inscricao', 'Congressista'), ('profissional', 'Profissional'), ('externo', 'Cliente Externo'), ('equipe', 'Equipe'), ('colaborador', 'Colaborador')], max_length=20, null=True),
        ),
    ]
