# Generated by Django 5.1.4 on 2025-09-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0017_alter_pedidocamisa_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaileAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteBaile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('baile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='danca.baileavulso')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.lote')),
            ],
        ),
    ]
