# Generated by Django 5.1.4 on 2025-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0018_baileavulso_participantebaile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baileavulso',
            name='gasto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gasto total com este baile (ex.: aluguel, músicos etc.)', max_digits=10),
        ),
    ]
