# Generated by Django 5.1.4 on 2025-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0019_baileavulso_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantebaile',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado ao valor do lote', max_digits=10),
        ),
    ]
